export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const RETRIEVE_QUESTIONS_REQUEST = "RETRIEVE_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_LOADING = "FETCH_QUESTIONS_LOADING";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
